import os
import traceback

import gradio as gr
from PIL import Image

from pipeline import MisinformationPipeline
from analytics import SimulationAnalytics
from config import (
    NETWORK_NUM_NODES, NETWORK_EDGES_PER_NODE,
    SPREAD_PROBABILITY, AMPLIFICATION_FACTOR,
    calculate_agent_counts,
)


pipeline_instance = None


def initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification,
                         num_influencers, num_fact_checkers, num_moderators):

    spread_prob_value = float(spread_prob)
    if spread_prob_value > 1:
        spread_prob_value = spread_prob_value / 100.0

    global pipeline_instance
    pipeline_instance = MisinformationPipeline(
        num_nodes=int(num_nodes),
        edges_per_node=int(edges_per_node),
        spread_prob=spread_prob_value,
        amplification=int(amplification),
        num_influencers=int(num_influencers),
        num_fact_checkers=int(num_fact_checkers),
        num_moderators=int(num_moderators),
    )
    return pipeline_instance



def preview_network(num_nodes, edges_per_node, spread_prob, amplification,
                     num_influencers, num_fact_checkers, num_moderators):
    try:
        pipe = initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification,
                                    num_influencers, num_fact_checkers, num_moderators)
        path = pipe.network.visualize_network(
            title=f"Social Network Preview — {int(num_nodes)} Nodes",
            save_path="network_preview.png",
        )
        stats = pipe.network.get_network_stats()

        normal_count = (int(num_nodes) - 1
                        - int(num_influencers)
                        - int(num_fact_checkers)
                        - int(num_moderators))

        stats_text = (
            f"📊 Network Statistics\n{'─'*40}\n"
            f"Total Nodes    : {stats['total_nodes']}\n"
            f"Total Edges    : {stats['total_edges']}\n"
            f"Avg Degree     : {int(round(stats['avg_degree']))}\n"
            f"Max Degree     : {stats['max_degree']}\n"
            f"Density        : {int(round(stats['density'] * 100))}%\n"
            f"Avg Clustering : {int(round(stats['avg_clustering'] * 100))}%\n"
            f"Connected      : {'✅' if stats.get('connected') else '❌'}\n\n"
            f"🤖 Agent Configuration\n{'─'*40}\n"
            f"🔴 Misinfo Source : 1\n"
            f"🟠 Influencers    : {int(num_influencers)}\n"
            f"🟢 Fact-Checkers  : {int(num_fact_checkers)}\n"
            f"🟣 Moderators     : {int(num_moderators)}\n"
            f"🔵 Normal Users   : {max(0, normal_count)}"
        )

        if os.path.exists(path):
            return Image.open(path), stats_text
    except Exception as e:
        return None, f"❌ Preview failed: {e}"
    return None, "❌ Failed to generate preview"



def run_simulation(num_nodes, edges_per_node, spread_prob, amplification,
                    num_influencers, num_fact_checkers, num_moderators):
    
    empty_table = [["—", "—", "—", "—"]]
    empty_node_table = [["—", "—", "—", "—"]]
    empty = ("", "", "", "", "", "", "", None, None, "", empty_table, empty_node_table)

    try:
        pipe = initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification,
                                    num_influencers, num_fact_checkers, num_moderators)
        result = pipe.run_simulation()

        # Analytics
        analytics_engine = SimulationAnalytics(pipe.network)

        # ── Claim output ──────────────────────────────────────────
        claim = result.get("claim", {})
        claim_output = (
            f"📰 Generated Misinformation Claim\n{'─'*50}\n"
            f"📝 Claim: {claim.get('claim', 'N/A')}\n"
            f"🏷️ Topic: {claim.get('topic', 'N/A')}\n"
            f"🤖 Generated by: {claim.get('generated_by', 'N/A')}\n"
        )
        injection = result.get("injection_result", {})
        if injection.get("success"):
            claim_output += (
                f"\n📍 Injection Point\n{'─'*50}\n"
                f"Node: {injection.get('source_label', 'N/A')}\n"
                f"Degree: {injection.get('degree', 'N/A')} connections\n"
            )

        # ── Spread output ─────────────────────────────────────────
        spread = result.get("spread_result", {})
        spread_output = (
            f"📡 Neutral Agent — BFS Spread\n{'─'*50}\n"
            f"Nodes Infected    : {spread.get('total_spread', 0)} / {spread.get('total_nodes', 0)}\n"
            f"Penetration Rate  : {int(round(spread.get('penetration_rate', 0)))}%\n"
            f"Max Spread Depth  : {spread.get('max_depth', 0)} hops\n"
            f"Normal Users Hit  : {spread.get('normal_users_infected', 0)}\n"
        )

        # ── Influencer output ─────────────────────────────────────
        influence = result.get("influence_result", {})
        influencer_output = (
            f"📣 Influencer Agent — Amplification\n{'─'*50}\n"
            f"Active Influencers : {influence.get('active_influencers', 0)}\n"
            f"Additional Spread  : {influence.get('additional_spread', 0)} nodes\n"
            f"Amplification Score: {int(round(influence.get('amplification_score', 0)))}/10\n\n"
            f"✍️ Modified Claim:\n{influence.get('modified_claim', 'N/A')[:200]}\n"
        )

        # ── Fact-check output ─────────────────────────────────────
        fc = result.get("fact_check_result", {})
        emoji = {"Real": "✅", "Fake": "❌", "Unverified": "⚠️"}.get(fc.get("verdict"), "❓")
        fc_output = (
            f"🔍 Fact-Checker Agent — Verification\n{'─'*50}\n"
            f"{emoji} Verdict    : {fc.get('verdict', 'N/A')}\n"
            f"📊 Confidence : {fc.get('confidence', 0)*100:.0f}%\n"
            f"📝 Evidence   : {fc.get('evidence', 'N/A')[:200]}\n"
            f"🌐 Search Engine: {fc.get('search_provider', 'duckduckgo')}\n"
            f"🔎 Search Note  : {fc.get('search_summary', 'No web-search summary available.')}\n"
            f"📋 Nodes Checked: {fc.get('nodes_checked', 0)}\n"
            f"⚠️ Nodes Warned : {fc.get('nodes_warned', 0)}\n"
            f"🔍 Active Checkers: {fc.get('active_checkers', 0)} / {fc.get('total_fact_checkers', 0)}\n"
        )
        flags = fc.get("red_flags", [])
        if flags:
            fc_output += f"\n🚩 Red Flags:\n" + "\n".join(f"  • {f}" for f in flags)

        sources = fc.get("search_sources", [])
        if sources:
            fc_output += "\n\n📚 Sources Checked:\n"
            for idx, src in enumerate(sources[:5], start=1):
                title = src.get("title", "Untitled")
                url = src.get("url", "N/A")
                snippet = src.get("snippet", "")[:140]
                fc_output += (
                    f"  {idx}. {title}\n"
                    f"     Website: {url}\n"
                    f"     Found: {snippet}\n"
                )

        # ── Moderation output ─────────────────────────────────────
        mod = result.get("moderation_result", {})
        d_emoji = {"BLOCK": "🚫", "FLAG": "⚠️", "ALLOW": "✅"}.get(mod.get("decision"), "❓")
        moderation_output = (
            f"🛡️ Moderator Agent — Action\n{'─'*50}\n"
            f"{d_emoji} Decision : {mod.get('decision', 'N/A')}\n"
            f"🔴 Severity : {mod.get('severity', 'N/A')}\n"
            f"📝 Reason   : {mod.get('reason', 'N/A')}\n"
            f"⚡ Action   : {mod.get('action_taken', 'N/A')}\n\n"
            f"📊 Moderation Impact:\n"
            f"  🚫 Blocked: {mod.get('nodes_blocked', 0)} nodes\n"
            f"  ⚠️ Flagged: {mod.get('nodes_flagged', 0)} nodes\n"
            f"  ✅ Allowed: {mod.get('nodes_allowed', 0)} nodes\n"
            f"  👮 Active Moderators: {mod.get('active_moderators', 0)} / {mod.get('total_moderators', 0)}\n"
        )

        # ── Pipeline log ──────────────────────────────────────────
        log = "\n".join(result.get("pipeline_log", []))
        log += f"\n\n⏱️ Total Time: {int(round(result.get('elapsed_time', 0)))}s"

        # ── Analytics report ──────────────────────────────────────
        analytics_report = analytics_engine.generate_analytics_report(result)

        # ── Images ────────────────────────────────────────────────
        network_img = None
        analysis_img = None
        graph_path = result.get("network_graph_path", "network_graph.png")
        chart_path = result.get("analysis_chart_path", "spread_analysis.png")
        if os.path.exists(graph_path):
            network_img = Image.open(graph_path)
        if os.path.exists(chart_path):
            analysis_img = Image.open(chart_path)

        # ── Full report ───────────────────────────────────────────
        full_report = pipe.get_full_report(result)

        # ── Agent activity table ──────────────────────────────────
        agent_table = analytics_engine.compute_agent_activity(result)

        # ── Node breakdown table ──────────────────────────────────
        node_table = analytics_engine.compute_node_breakdown(result)

        return (
            claim_output,
            spread_output,
            influencer_output,
            fc_output,
            moderation_output,
            log,
            analytics_report,
            network_img,
            analysis_img,
            full_report,
            agent_table,
            node_table,
        )

    except Exception as e:
        err = f"❌ Simulation Error: {e}\n\n{traceback.format_exc()}"
        return (err, "", "", "", "", err, "", None, None, err, empty_table, empty_node_table)


# ─── Build the Gradio Interface ──────────────────────────────────────────────

CUSTOM_CSS = """
:root {
    --ink: #102a43;
    --paper: #f7f6f2;
    --accent: #ff7a18;
    --accent-2: #0f766e;
    --card: #fffdf7;
}

body {
    background: radial-gradient(circle at 20% 10%, #ffe8cc 0, #f7f6f2 40%, #e6f4ea 100%) !important;
}

.gradio-container {
    max-width: 1500px !important;
}

.block {
    border: 1px solid #eadfcf !important;
    background: var(--card) !important;
    border-radius: 16px !important;
    box-shadow: 0 10px 30px rgba(16, 42, 67, 0.07) !important;
}

button.primary {
    background: linear-gradient(90deg, var(--accent), #ffb347) !important;
    border: none !important;
    color: #1a1205 !important;
    font-weight: 700 !important;
}

button.secondary {
    background: linear-gradient(90deg, #d1fae5, #a7f3d0) !important;
    border: 1px solid #67e8f9 !important;
    color: #083344 !important;
    font-weight: 700 !important;
}

.tabs button {
    border-radius: 999px !important;
}
"""

GRADIO_THEME = gr.themes.Soft(
        primary_hue="amber", secondary_hue="emerald", neutral_hue="stone",
)


def update_agent_defaults(num_nodes):
    """Called when node-count slider changes — returns recommended agent counts."""
    defaults = calculate_agent_counts(int(num_nodes))
    return (
        gr.update(value=defaults["num_influencers"]),
        gr.update(value=defaults["num_fact_checkers"]),
        gr.update(value=defaults["num_moderators"]),
    )

def create_ui():
    """Create and return the Gradio Blocks app."""

    defaults = calculate_agent_counts(NETWORK_NUM_NODES)

    with gr.Blocks(
        title="Multi-Agent Misinformation Simulation",
    ) as app:

        # ─── Header ──────────────────────────────────────────────────
        gr.Markdown("""
# 🛡️ AI Multi-Agent Misinformation Simulation System
### Sequential Pipeline: Misinformation → Neutral Spread → Influencer → Fact-Checker → Moderator
 Simulating Social Network Information Dynamics*
---
        """)

        with gr.Tabs():
            # ━━━ TAB 1: SIMULATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("🚀 Run Simulation", id="simulation"):

                with gr.Row():
                    # ── Left column: Config ──────────────────────────
                    with gr.Column(scale=1):
                        gr.Markdown("### ⚙️ Network Configuration")
                        gr.Markdown(
                            "*Agent counts are auto-calculated based on graph size. "
                            "API key is loaded from `.env` file.*"
                        )
                        num_nodes_slider = gr.Slider(
                            minimum=100, maximum=1000, value=NETWORK_NUM_NODES, step=50,
                            label="Number of Nodes",
                            info="Graph size (100-1000 nodes)",
                        )
                        edges_slider = gr.Slider(
                            minimum=1, maximum=8, value=NETWORK_EDGES_PER_NODE, step=1,
                            label="Edges per Node (m)",
                            info="Connection density",
                        )

                        gr.Markdown("### 📡 Propagation Settings")
                        spread_prob_slider = gr.Slider(
                            minimum=5, maximum=90, value=int(SPREAD_PROBABILITY * 100), step=5,
                            label="Base Spread Probability (%)",
                            info="Integer percentage chance a normal user reshares",
                        )
                        amplification_slider = gr.Slider(
                            minimum=1, maximum=5, value=int(AMPLIFICATION_FACTOR), step=1,
                            label="Influencer Amplification Factor",
                            info="Integer multiplier on neighbour fan-out",
                        )

                        gr.Markdown("### 🤖 Agent Configuration")
                        gr.Markdown(
                            "*Defaults are auto-calculated when you change the node count. "
                            "Feel free to override them.*"
                        )
                        influencer_slider = gr.Slider(
                            minimum=1, maximum=50,
                            value=defaults["num_influencers"], step=1,
                            label="🟠 Number of Influencer Agents",
                            info="High-degree nodes that amplify claims",
                        )
                        fact_checker_slider = gr.Slider(
                            minimum=1, maximum=50,
                            value=defaults["num_fact_checkers"], step=1,
                            label="🟢 Number of Fact-Checker Agents",
                            info="Nodes that verify and warn neighbours",
                        )
                        moderator_slider = gr.Slider(
                            minimum=1, maximum=50,
                            value=defaults["num_moderators"], step=1,
                            label="🟣 Number of Moderator Agents",
                            info="Content gatekeepers that block/flag",
                        )

                        with gr.Row():
                            preview_btn = gr.Button("👁️ Preview Network", variant="secondary", size="lg")
                            run_btn = gr.Button("▶️ Run Simulation", variant="primary", size="lg")

                    # ── Right column: Preview ────────────────────────
                    with gr.Column(scale=1):
                        gr.Markdown("### 📊 Network Preview")
                        preview_stats = gr.Textbox(label="Network Statistics & Agent Counts", lines=18, interactive=False)

                preview_image = gr.Image(label="Network Graph Preview", type="pil", height=500)

                gr.Markdown("---")
                gr.Markdown("### 📋 Simulation Results — Sequential Agent Pipeline")

                with gr.Row():
                    with gr.Column():
                        claim_output = gr.Textbox(
                            label="🔴 Step 1: Misinformation Agent — Claim Generation",
                            lines=8, interactive=False,
                        )
                    with gr.Column():
                        spread_output = gr.Textbox(
                            label="🔵 Step 2: Neutral Agent — BFS Spread",
                            lines=8, interactive=False,
                        )

                with gr.Row():
                    with gr.Column():
                        influencer_output = gr.Textbox(
                            label="🟠 Step 3: Influencer Agent — Amplification",
                            lines=10, interactive=False,
                        )
                    with gr.Column():
                        fc_output = gr.Textbox(
                            label="🟢 Step 4: Fact-Checker Agent — Verification",
                            lines=10, interactive=False,
                        )

                moderation_output = gr.Textbox(
                    label="🟣 Step 5: Moderator Agent — Action",
                    lines=10, interactive=False,
                )

                pipeline_log = gr.Textbox(
                    label="📝 Pipeline Execution Log",
                    lines=15, interactive=False,
                )

            # ━━━ TAB 2: AGENT STATS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("🤖 Agents Working", id="agent_stats"):
                gr.Markdown("### 🤖 Agent Activity — How Each Agent Worked")
                gr.Markdown(
                    "*This table shows what each agent did during the simulation, "
                    "how many nodes it affected, and its key results.*"
                )
                agent_table = gr.Dataframe(
                    headers=["Agent", "Action", "Impact", "Details"],
                    label="Agent Activity Table",
                    interactive=False,
                    wrap=True,
                )

                gr.Markdown("---")
                gr.Markdown("### 📊 Node Status Breakdown")
                gr.Markdown(
                    "*Final status of all nodes after the complete simulation pipeline.*"
                )
                node_table = gr.Dataframe(
                    headers=["Status", "Count", "Percentage", "Description"],
                    label="Node Status Breakdown",
                    interactive=False,
                    wrap=True,
                )

            # ━━━ TAB 3: VISUALIZATIONS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📊 Visualizations", id="visualizations"):
                gr.Markdown("### 🌐 Social Network — Simulation Result")
                network_image = gr.Image(label="Network Graph", type="pil", height=650)
                gr.Markdown("### 📈 Analysis Dashboard")
                analysis_image = gr.Image(label="Analysis Charts", type="pil", height=650)

            # ━━━ TAB 4: ANALYTICS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📈 Detailed Analytics", id="analytics"):
                gr.Markdown("### 📊 Comprehensive Simulation Analytics")
                analytics_output = gr.Textbox(label="Analytics Report", lines=50, interactive=False)

            # ━━━ TAB 5: FULL REPORT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📄 Full Report", id="report"):
                gr.Markdown("### 📄 Complete Simulation Report")
                report_output = gr.Textbox(label="Full Report", lines=55, interactive=False)

            # ━━━ TAB 6: ABOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("ℹ️ About", id="about"):
                gr.Markdown("""
## About This Project

### 🎯 Project Title
**AI Multi-Agent System for Misinformation Spread, Verification and Moderation in Social Networks**

### 🔄 Sequential Agent Pipeline
Each simulation runs exactly **ONE claim** through **5 sequential agents**:

| Step | Agent | Role | Graph Action |
|------|-------|------|-------------|
| 1 | 🔴 **Misinformation Agent** | Generate claim | Injects claim via LLM into source node |
| 2 | 🔵 **Neutral Agent** | BFS Spread | Normal users reshare through the network |
| 3 | 🟠 **Influencer Agent** | Amplify & Modify | Rewrites claim, spreads to more neighbours |
| 4 | 🟢 **Fact-Checker Agent** | Verify & Warn | Checks claim, attaches warnings to nodes |
| 5 | 🟣 **Moderator Agent** | Block/Flag/Allow | Takes action based on fact-checker verdict |

### 🤖 Auto-Calculated Agents
Agent counts are automatically determined based on graph size:
- **1 Misinfo Source** (always single claim)
- **~5% Influencers** (high-degree nodes)
- **~8% Fact-Checkers** (verification nodes)
- **~10% Moderators** (content gatekeepers)
- **Remaining → Normal Users** (base spreaders)

### 🛠️ Technology Stack
Python · NetworkX (Barabási-Albert) · LangGraph · Groq (LLaMA 3.3 70B)
· Gradio · Matplotlib · NumPy
                """)

        # ─── Inputs list (shared by preview & run) ───────────────────
        all_inputs = [
            num_nodes_slider, edges_slider,
            spread_prob_slider, amplification_slider,
            influencer_slider, fact_checker_slider, moderator_slider,
        ]

        # ─── Auto-update agent sliders when node count changes ───────
        num_nodes_slider.change(
            fn=update_agent_defaults,
            inputs=[num_nodes_slider],
            outputs=[influencer_slider, fact_checker_slider, moderator_slider],
        )

        # ─── Event Handlers ──────────────────────────────────────────
        preview_btn.click(
            fn=preview_network,
            inputs=all_inputs,
            outputs=[preview_image, preview_stats],
        )

        run_btn.click(
            fn=run_simulation,
            inputs=all_inputs,
            outputs=[
                claim_output, spread_output,
                influencer_output, fc_output,
                moderation_output, pipeline_log,
                analytics_output,
                network_image, analysis_image,
                report_output,
                agent_table, node_table,
            ],
        )

    return app


# ─── Launch ───────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app = create_ui()
    app.launch(
        share=False, server_name="0.0.0.0", server_port=7869, theme=GRADIO_THEME, css=CUSTOM_CSS,
    )
