"""
Gradio UI — Graph-Based Multi-Agent Misinformation Simulation System
=====================================================================
Provides an interactive web interface with configurable network size,
sequential agent pipeline visualization, agent stats tables, and
analytical dashboards.

API key is loaded from .env — no UI input needed.
Agent counts are auto-calculated based on graph size.
"""
import os
import traceback

import gradio as gr
from PIL import Image

from pipeline import MisinformationPipeline
from analytics import SimulationAnalytics
from config import (
    NETWORK_NUM_NODES, NETWORK_EDGES_PER_NODE,
    SPREAD_PROBABILITY, AMPLIFICATION_FACTOR,
    calculate_agent_counts,
)


# ─── Global state ─────────────────────────────────────────────────────────────
pipeline_instance = None


def initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification):
    """Create (or recreate) the pipeline with the given parameters."""
    global pipeline_instance
    pipeline_instance = MisinformationPipeline(
        num_nodes=int(num_nodes),
        edges_per_node=int(edges_per_node),
        spread_prob=float(spread_prob),
        amplification=float(amplification),
    )
    return pipeline_instance


# ── Preview network ───────────────────────────────────────────────────────────

def preview_network(num_nodes, edges_per_node, spread_prob, amplification):
    """Generate and preview the social network graph (no cascade)."""
    try:
        pipe = initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification)
        path = pipe.network.visualize_network(
            title=f"Social Network Preview — {int(num_nodes)} Nodes",
            save_path="network_preview.png",
        )
        stats = pipe.network.get_network_stats()
        agents = calculate_agent_counts(int(num_nodes))

        stats_text = (
            f"📊 Network Statistics\n{'─'*40}\n"
            f"Total Nodes    : {stats['total_nodes']}\n"
            f"Total Edges    : {stats['total_edges']}\n"
            f"Avg Degree     : {stats['avg_degree']}\n"
            f"Max Degree     : {stats['max_degree']}\n"
            f"Density        : {stats['density']}\n"
            f"Avg Clustering : {stats['avg_clustering']}\n"
            f"Connected      : {'✅' if stats.get('connected') else '❌'}\n\n"
            f"🤖 Auto-Assigned Agents\n{'─'*40}\n"
            f"🔴 Misinfo Source : {agents['num_misinfo']}\n"
            f"🟠 Influencers    : {agents['num_influencers']}\n"
            f"🟢 Fact-Checkers  : {agents['num_fact_checkers']}\n"
            f"🟣 Moderators     : {agents['num_moderators']}\n"
            f"🔵 Normal Users   : {stats['total_nodes'] - agents['num_misinfo'] - agents['num_influencers'] - agents['num_fact_checkers'] - agents['num_moderators']}"
        )

        if os.path.exists(path):
            return Image.open(path), stats_text
    except Exception as e:
        return None, f"❌ Preview failed: {e}"
    return None, "❌ Failed to generate preview"


# ── Simulation runner ─────────────────────────────────────────────────────────

def run_simulation(num_nodes, edges_per_node, spread_prob, amplification):
    """Execute the full sequential simulation and return UI outputs."""
    empty_table = [["—", "—", "—", "—"]]
    empty_node_table = [["—", "—", "—", "—"]]
    empty = ("", "", "", "", "", "", "", None, None, "", empty_table, empty_node_table)

    try:
        pipe = initialize_pipeline(num_nodes, edges_per_node, spread_prob, amplification)
        result = pipe.run_simulation()

        # Analytics
        analytics_engine = SimulationAnalytics(pipe.network)

        # ── Claim output ──────────────────────────────────────────
        claim = result.get("claim", {})
        claim_output = (
            f"📰 Generated Misinformation Claim\n{'─'*50}\n"
            f"📝 Claim: {claim.get('claim', 'N/A')}\n"
            f"🏷️ Topic: {claim.get('topic', 'N/A')}\n"
            f"🤖 Generated by: {claim.get('generated_by', 'N/A')}\n"
        )
        injection = result.get("injection_result", {})
        if injection.get("success"):
            claim_output += (
                f"\n📍 Injection Point\n{'─'*50}\n"
                f"Node: {injection.get('source_label', 'N/A')}\n"
                f"Degree: {injection.get('degree', 'N/A')} connections\n"
            )

        # ── Spread output ─────────────────────────────────────────
        spread = result.get("spread_result", {})
        spread_output = (
            f"📡 Neutral Agent — BFS Spread\n{'─'*50}\n"
            f"Nodes Infected    : {spread.get('total_spread', 0)} / {spread.get('total_nodes', 0)}\n"
            f"Penetration Rate  : {spread.get('penetration_rate', 0)}%\n"
            f"Max Spread Depth  : {spread.get('max_depth', 0)} hops\n"
            f"Normal Users Hit  : {spread.get('normal_users_infected', 0)}\n"
        )

        # ── Influencer output ─────────────────────────────────────
        influence = result.get("influence_result", {})
        influencer_output = (
            f"📣 Influencer Agent — Amplification\n{'─'*50}\n"
            f"Active Influencers : {influence.get('active_influencers', 0)}\n"
            f"Additional Spread  : {influence.get('additional_spread', 0)} nodes\n"
            f"Amplification Score: {influence.get('amplification_score', 0)}/10\n\n"
            f"✍️ Modified Claim:\n{influence.get('modified_claim', 'N/A')[:200]}\n"
        )

        # ── Fact-check output ─────────────────────────────────────
        fc = result.get("fact_check_result", {})
        emoji = {"Real": "✅", "Fake": "❌", "Unverified": "⚠️"}.get(fc.get("verdict"), "❓")
        fc_output = (
            f"🔍 Fact-Checker Agent — Verification\n{'─'*50}\n"
            f"{emoji} Verdict    : {fc.get('verdict', 'N/A')}\n"
            f"📊 Confidence : {fc.get('confidence', 0)*100:.0f}%\n"
            f"📝 Evidence   : {fc.get('evidence', 'N/A')[:200]}\n"
            f"📋 Nodes Checked: {fc.get('nodes_checked', 0)}\n"
            f"⚠️ Nodes Warned : {fc.get('nodes_warned', 0)}\n"
            f"🔍 Active Checkers: {fc.get('active_checkers', 0)} / {fc.get('total_fact_checkers', 0)}\n"
        )
        flags = fc.get("red_flags", [])
        if flags:
            fc_output += f"\n🚩 Red Flags:\n" + "\n".join(f"  • {f}" for f in flags)

        # ── Moderation output ─────────────────────────────────────
        mod = result.get("moderation_result", {})
        d_emoji = {"BLOCK": "🚫", "FLAG": "⚠️", "ALLOW": "✅"}.get(mod.get("decision"), "❓")
        moderation_output = (
            f"🛡️ Moderator Agent — Action\n{'─'*50}\n"
            f"{d_emoji} Decision : {mod.get('decision', 'N/A')}\n"
            f"🔴 Severity : {mod.get('severity', 'N/A')}\n"
            f"📝 Reason   : {mod.get('reason', 'N/A')}\n"
            f"⚡ Action   : {mod.get('action_taken', 'N/A')}\n\n"
            f"📊 Moderation Impact:\n"
            f"  🚫 Blocked: {mod.get('nodes_blocked', 0)} nodes\n"
            f"  ⚠️ Flagged: {mod.get('nodes_flagged', 0)} nodes\n"
            f"  ✅ Allowed: {mod.get('nodes_allowed', 0)} nodes\n"
            f"  👮 Active Moderators: {mod.get('active_moderators', 0)} / {mod.get('total_moderators', 0)}\n"
        )

        # ── Pipeline log ──────────────────────────────────────────
        log = "\n".join(result.get("pipeline_log", []))
        log += f"\n\n⏱️ Total Time: {result.get('elapsed_time', 0):.1f}s"

        # ── Analytics report ──────────────────────────────────────
        analytics_report = analytics_engine.generate_analytics_report(result)

        # ── Images ────────────────────────────────────────────────
        network_img = None
        analysis_img = None
        graph_path = result.get("network_graph_path", "network_graph.png")
        chart_path = result.get("analysis_chart_path", "spread_analysis.png")
        if os.path.exists(graph_path):
            network_img = Image.open(graph_path)
        if os.path.exists(chart_path):
            analysis_img = Image.open(chart_path)

        # ── Full report ───────────────────────────────────────────
        full_report = pipe.get_full_report(result)

        # ── Agent activity table ──────────────────────────────────
        agent_table = analytics_engine.compute_agent_activity(result)

        # ── Node breakdown table ──────────────────────────────────
        node_table = analytics_engine.compute_node_breakdown(result)

        return (
            claim_output,
            spread_output,
            influencer_output,
            fc_output,
            moderation_output,
            log,
            analytics_report,
            network_img,
            analysis_img,
            full_report,
            agent_table,
            node_table,
        )

    except Exception as e:
        err = f"❌ Simulation Error: {e}\n\n{traceback.format_exc()}"
        return (err, "", "", "", "", err, "", None, None, err, empty_table, empty_node_table)


# ─── Build the Gradio Interface ──────────────────────────────────────────────

CUSTOM_CSS = """
.gradio-container { max-width: 1500px !important; }
"""

GRADIO_THEME = gr.themes.Soft(
    primary_hue="blue", secondary_hue="purple", neutral_hue="slate",
)


def create_ui():
    """Create and return the Gradio Blocks app."""

    with gr.Blocks(
        title="Multi-Agent Misinformation Simulation",
        theme=GRADIO_THEME,
        css=CUSTOM_CSS,
    ) as app:

        # ─── Header ──────────────────────────────────────────────────
        gr.Markdown("""
# 🛡️ AI Multi-Agent Misinformation Simulation System
### Sequential Pipeline: Misinformation → Neutral Spread → Influencer → Fact-Checker → Moderator
*MCA Final Year Project — Simulating Social Network Information Dynamics*
---
        """)

        with gr.Tabs():
            # ━━━ TAB 1: SIMULATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("🚀 Run Simulation", id="simulation"):

                with gr.Row():
                    # ── Left column: Config ──────────────────────────
                    with gr.Column(scale=1):
                        gr.Markdown("### ⚙️ Network Configuration")
                        gr.Markdown(
                            "*Agent counts are auto-calculated based on graph size. "
                            "API key is loaded from `.env` file.*"
                        )
                        num_nodes_slider = gr.Slider(
                            minimum=100, maximum=1000, value=NETWORK_NUM_NODES, step=50,
                            label="Number of Nodes",
                            info="Graph size (100-1000 nodes)",
                        )
                        edges_slider = gr.Slider(
                            minimum=1, maximum=8, value=NETWORK_EDGES_PER_NODE, step=1,
                            label="Edges per Node (m)",
                            info="Connection density",
                        )

                        gr.Markdown("### 📡 Propagation Settings")
                        spread_prob_slider = gr.Slider(
                            minimum=0.05, maximum=0.90, value=SPREAD_PROBABILITY, step=0.05,
                            label="Base Spread Probability",
                            info="Chance a normal user reshares",
                        )
                        amplification_slider = gr.Slider(
                            minimum=1.0, maximum=5.0, value=AMPLIFICATION_FACTOR, step=0.5,
                            label="Influencer Amplification Factor",
                            info="Multiplier on neighbour fan-out",
                        )

                        with gr.Row():
                            preview_btn = gr.Button("👁️ Preview Network", variant="secondary", size="lg")
                            run_btn = gr.Button("▶️ Run Simulation", variant="primary", size="lg")

                    # ── Right column: Preview ────────────────────────
                    with gr.Column(scale=1):
                        gr.Markdown("### 📊 Network Preview")
                        preview_stats = gr.Textbox(label="Network Statistics & Agent Counts", lines=18, interactive=False)

                preview_image = gr.Image(label="Network Graph Preview", type="pil", height=500)

                gr.Markdown("---")
                gr.Markdown("### 📋 Simulation Results — Sequential Agent Pipeline")

                with gr.Row():
                    with gr.Column():
                        claim_output = gr.Textbox(
                            label="🔴 Step 1: Misinformation Agent — Claim Generation",
                            lines=8, interactive=False,
                        )
                    with gr.Column():
                        spread_output = gr.Textbox(
                            label="🔵 Step 2: Neutral Agent — BFS Spread",
                            lines=8, interactive=False,
                        )

                with gr.Row():
                    with gr.Column():
                        influencer_output = gr.Textbox(
                            label="🟠 Step 3: Influencer Agent — Amplification",
                            lines=10, interactive=False,
                        )
                    with gr.Column():
                        fc_output = gr.Textbox(
                            label="🟢 Step 4: Fact-Checker Agent — Verification",
                            lines=10, interactive=False,
                        )

                moderation_output = gr.Textbox(
                    label="🟣 Step 5: Moderator Agent — Action",
                    lines=10, interactive=False,
                )

                pipeline_log = gr.Textbox(
                    label="📝 Pipeline Execution Log",
                    lines=15, interactive=False,
                )

            # ━━━ TAB 2: AGENT STATS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("🤖 Agents Working", id="agent_stats"):
                gr.Markdown("### 🤖 Agent Activity — How Each Agent Worked")
                gr.Markdown(
                    "*This table shows what each agent did during the simulation, "
                    "how many nodes it affected, and its key results.*"
                )
                agent_table = gr.Dataframe(
                    headers=["Agent", "Action", "Impact", "Details"],
                    label="Agent Activity Table",
                    interactive=False,
                    wrap=True,
                )

                gr.Markdown("---")
                gr.Markdown("### 📊 Node Status Breakdown")
                gr.Markdown(
                    "*Final status of all nodes after the complete simulation pipeline.*"
                )
                node_table = gr.Dataframe(
                    headers=["Status", "Count", "Percentage", "Description"],
                    label="Node Status Breakdown",
                    interactive=False,
                    wrap=True,
                )

            # ━━━ TAB 3: VISUALIZATIONS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📊 Visualizations", id="visualizations"):
                gr.Markdown("### 🌐 Social Network — Simulation Result")
                network_image = gr.Image(label="Network Graph", type="pil", height=650)
                gr.Markdown("### 📈 Analysis Dashboard")
                analysis_image = gr.Image(label="Analysis Charts", type="pil", height=650)

            # ━━━ TAB 4: ANALYTICS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📈 Detailed Analytics", id="analytics"):
                gr.Markdown("### 📊 Comprehensive Simulation Analytics")
                analytics_output = gr.Textbox(label="Analytics Report", lines=50, interactive=False)

            # ━━━ TAB 5: FULL REPORT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("📄 Full Report", id="report"):
                gr.Markdown("### 📄 Complete Simulation Report")
                report_output = gr.Textbox(label="Full Report", lines=55, interactive=False)

            # ━━━ TAB 6: ABOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            with gr.TabItem("ℹ️ About", id="about"):
                gr.Markdown("""
## About This Project

### 🎯 Project Title
**AI Multi-Agent System for Misinformation Spread, Verification and Moderation in Social Networks**

### 🔄 Sequential Agent Pipeline
Each simulation runs exactly **ONE claim** through **5 sequential agents**:

| Step | Agent | Role | Graph Action |
|------|-------|------|-------------|
| 1 | 🔴 **Misinformation Agent** | Generate claim | Injects claim via LLM into source node |
| 2 | 🔵 **Neutral Agent** | BFS Spread | Normal users reshare through the network |
| 3 | 🟠 **Influencer Agent** | Amplify & Modify | Rewrites claim, spreads to more neighbours |
| 4 | 🟢 **Fact-Checker Agent** | Verify & Warn | Checks claim, attaches warnings to nodes |
| 5 | 🟣 **Moderator Agent** | Block/Flag/Allow | Takes action based on fact-checker verdict |

### 🤖 Auto-Calculated Agents
Agent counts are automatically determined based on graph size:
- **1 Misinfo Source** (always single claim)
- **~5% Influencers** (high-degree nodes)
- **~8% Fact-Checkers** (verification nodes)
- **~10% Moderators** (content gatekeepers)
- **Remaining → Normal Users** (base spreaders)

### 🛠️ Technology Stack
Python · NetworkX (Barabási-Albert) · LangGraph · Groq (LLaMA 3.3 70B)
· Gradio · Matplotlib · NumPy
                """)

        # ─── Inputs list (shared by preview & run) ───────────────────
        all_inputs = [
            num_nodes_slider, edges_slider,
            spread_prob_slider, amplification_slider,
        ]

        # ─── Event Handlers ──────────────────────────────────────────
        preview_btn.click(
            fn=preview_network,
            inputs=all_inputs,
            outputs=[preview_image, preview_stats],
        )

        run_btn.click(
            fn=run_simulation,
            inputs=all_inputs,
            outputs=[
                claim_output, spread_output,
                influencer_output, fc_output,
                moderation_output, pipeline_log,
                analytics_output,
                network_image, analysis_image,
                report_output,
                agent_table, node_table,
            ],
        )

    return app


# ─── Launch ───────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app = create_ui()
    app.launch(
        share=False, server_name="0.0.0.0", server_port=7860,
    )
